### ISSUE TITLE
Github releases

### ISSUE THREAD

**Issue by johanvanmol** [buildingsmart-community/bSDD-Revit-plugin#40]
Is it on the roadmap to publish releases of this Revit add-in?
For instance: [pyRevit ](https://github.com/eirannejad/pyRevit) is using this Github feature.

![afbeelding](https://github.com/buildingsmart-community/bSDD-Revit-plugin/assets/820474/b8327b93-7af1-42a6-8079-a702ef8e9379)

It would be nice to have a installer, so that a lot of non-technical users can download and install this Revit add-in.
For instance:
![afbeelding](https://github.com/buildingsmart-community/bSDD-Revit-plugin/assets/820474/2711bb11-0304-4b65-b180-cc228f44af91)

**Comment by jbrouwerdigibase** [comment]
https://github.com/buildingsmart-community/bSDD-Revit-plugin/releases/tag/v1.0.0_beta
