### ISSUE TITLE
switch to production environment

### ISSUE THREAD

**Issue by atomczak** [buildingsmart-community/bSDD-Revit-plugin#60]
Hi! By default, the plugin was set to pull content from TEST server and using Basis Bouwproducten as main and IFC and SFB as filters. I would like to use Production server instead but after switching to 'production' the dropdown list stays the same. How can I connect to Production? 

Also, the TEST server is meant for developers only, not for testing new content, so I suggest to hide it for general users and only enable in some debug mode if needed. 

Instead, there could be a toggle to also see content marked as 'Test' on the Production server. Yes, we have TEST server and TEST content on PROD server... :) To see the test content from PROD you need to set the IncludeTestDictionaries to TRUE on the GET /api/Dictionary/v1. 

![image](https://github.com/buildingsmart-community/bSDD-Revit-plugin/assets/22922395/46867180-5962-4663-a8e2-891069e7b4b0)

**Comment by jbrouwerdigibase** [comment]
That's something we are currently improving, currently you can switch by first selecting production, then save, and then change the dictionaries.

**Comment by jbrouwerdigibase** [comment]
Should be fixed in https://github.com/buildingsmart-community/bSDD-Revit-plugin/pull/66
