### ISSUE TITLE
Existing IfcPropertySet and IfcProperty data not read in UI

### ISSUE THREAD

**Issue by jbrouwerdigibase** [buildingsmart-community/bSDD-Revit-plugin#68]
**Describe the issue** The UI does not display existing IfcPropertySet and IfcProperty data that has been previously saved from the bSDD. When reselecting the same Revit type, these existing properties should be shown in the UI for modification, but currently, they are not.

**To Reproduce** Steps to reproduce the behavior:

1. Save IfcPropertySet and IfcProperty data from the bSDD.
2. Reselect the same Revit type.
3. Notice that the previously saved properties are not displayed in the UI.

**Expected behavior** When reselecting the same Revit type, the UI should display the existing IfcPropertySet and IfcProperty data that was previously saved from the bSDD. This would allow the user to modify these properties as needed.

**Comment by Rien777** [comment]
This has been added, also for classifications from beta v1.1.2 and higher.
