### ISSUE TITLE
UI terminology 

### ISSUE THREAD

**Issue by xpt5** [buildingsmart-community/bSDD-Revit-plugin#73]
Hi and thank you very much for starting developing the bSDD Revit plugin. I think a lot of people in the AEC industry will benefit from it.

**Problem Description:**
Since I am quite new to the concept of bSDD my comment might be quite wrong, but here it goes anyways.
According to the bSDD buildindSMART [introduction video](https://vimeo.com/556089138) (2021) by Frederic Grand I understood that the bSDD content was organized by different "domains" and the dictionary is only one (bSDD). At the video min 06:50 he explains the concept by giving the example of NL-SfB 2015 and IFC domains information mapping. This plugin is trying to do the same so that the right information can be added to the Revit object, so why not replace dictionary/dictionaries with domain/domains in the plugin UI? I was a bit confused when I opened the plugin since it didn't make sense to me based on that video introduction.

Is my interpretation completely wrong or outdated? If not, should the UI reflect that terminology? What do you think? 

**Software version:** 
1.0.5 beta

![Revit_FxUPWLCgk6](https://github.com/buildingsmart-community/bSDD-Revit-plugin/assets/30028308/0d3468b8-78e2-4539-8856-533a8d871469)

**Comment by jbrouwerdigibase** [comment]
Hi Joao,

buildingSMART changed a lot of terminology last year after feedback from the linked data community.

for example:
**domain** changed to **dictionary**
**classification** to **class**

So the UI should be consistent with the latest version of bSDD.

**Comment by xpt5** [comment]
@jbrouwerdigibase  thank you very much for the feedback.
