### ISSUE TITLE
Settings reverts back to default after loading a Family

### ISSUE THREAD

**Issue by MennoMekes** [buildingsmart-community/bSDD-Revit-plugin#93]
After aditing a Fmaily and loading it back in, the Settings reverts back to default.

**Comment by janbrouwer** [comment]
@Rien777 @ebouwens can one of you take a look at this?

**Comment by ebouwens** [comment]
I think we ll need some more information here, witch settings we specificly talking here about? The settings in the family itself (maybe an example can be given) or is the settings (linked BSDD database, ect) of the tool reverted?

**Comment by Rien777** [comment]
@MennoMekes @ebouwens 

I tested this and it works like it should, when:
- Editing a family 
- Loading a family
Returning to your project should set the projectsettings back to their specific settings. 

This was added on the 9th of july:
https://github.com/buildingsmart-community/bSDD-Revit-plugin/blame/9e3e1669bf20e4cf73338f0b4d4fd98800a7dd51/BsddRevitPlugin.Common/Startup.cs#L118

On the roadmap:
- Optional bringing project settings to familly when editing family
- Family-mode when editing family where just the current family is getting checked in the element-list

**Comment by MennoMekes** [comment]
I can't reproduce it anymore either.
