### ISSUE TITLE
Suggestion: Sort on Family name or Type in stead of Description

### ISSUE THREAD

**Issue by ReneSondermijer** [buildingsmart-community/bSDD-Revit-plugin#97]
First of all, I'm really pleased with the development of this plugin, it has great potential!

When using/testing it, I have the following small suggestion: Elements are now listed by their Description, which not always makes sense as sometimes the description isn't right, or is the same as other elements. My suggestion therefore is to list by Family and/or Type name which is much better recognizable.

Regards,

René

**Comment by Rien777** [comment]
Hello @ReneSondermijer , 

In the recent update v1.6.0 we added a few more options:
![image](https://github.com/user-attachments/assets/57b20a8d-b36d-42db-a1b6-b85e8bcba08a)

Will this do the trick for you or would you like more options?

**Comment by ReneSondermijer** [comment]
Hi @Rien777,

Yes, this having these different options makes searching elements much easier. Adding the Assembly Code to this list would also be really helplful.

Regards,

René
