### ISSUE TITLE
Searching based on synonyms

### ISSUE THREAD

**Issue by ReneSondermijer** [buildingsmart-community/bSDD-Revit-plugin#98]
At this moment, added synonyms to a class aren't working when searching in the bSDD Revit plugin. It would be very helpful if this could be implemented in the plugin, as this would make searching a lot more approachable.

I noticed that in the API documentation, the search function /api/Class/Search/v1 does make use of synonyms. 

Regards,

René Sondermeijer

**Comment by Rien777** [comment]
Thanks for the issue!

I moved to the UI project:
https://github.com/buildingsmart-community/bSDD-filter-UI/issues/41
